name: Claude Code Action Playwright Test
description: Claude Code Action Playwright Test
on:
  workflow_dispatch:

jobs:
  run-e2e-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: run todo app
        run: npm run serve &

      - name: Wait for server to be ready
        run: |
          timeout 30 bash -c 'until curl -f http://localhost:3000; do sleep 1; done'

      - name: Create prompt
        run: |
          mkdir -p /tmp/claude-prompts
          for file in test-instructions/*.md; do
            cat "$file"
            echo ""
          done > /tmp/claude-prompts/prompt.txt

      - name: Run Claude Code for Playwright Test
        id: exec-tests
        uses: anthropics/claude-code-base-action@beta
        with:
          prompt_file: /tmp/claude-prompts/prompt.txt
          system_prompt: "localhostのサーバーは起動済みです"
          allowed_tools: "Bash,mcp__playwright__"
          mcp_config: .mcp.json
          timeout_minutes: "5"
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
      
      - name: Upload Result
        if: steps.exec-tests.outputs.conclusion == 'success'
        uses: actions/upload-artifact@v4
        with:
          name: test-result.md
          path: ./test-result.md
          retention-days: 7